### ISSUE TITLE
Deployment on Scroll zk-Rollup

### ISSUE THREAD

**Issue by susumutomita** [susumutomita/ETHTokyo2024#14]
### Issue Title

[Feature] Deployment on Scroll zk-Rollup

### Description

Deploy smart contracts on Scroll's zk-rollup to enhance scalability and reduce transaction costs. Test the deployment on Scroll's testnet.

### Tasks

- [x] Configure development environment for Scroll
- [x] Deploy smart contracts on Scroll testnet
- [x] Optimize contracts for zk-rollup compatibility
- [x] Perform testing for performance and reliability

### Notes

Monitor gas costs and transaction speeds. Ensure compatibility with other Ethereum layer-2 solutions.

**Comment by susumutomita** [comment]
<img width="1471" alt="image" src="https://github.com/user-attachments/assets/25690869-f612-493a-ae04-853c12f59ffc">

0x624669da92762546073a8B00579835216F5FD4B4

https://sepolia.scrollscan.com/address/0x624669da92762546073a8B00579835216F5FD4B4
